### ISSUE TITLE
dq-view shortcut creates dolphin crashes

### ISSUE THREAD

**Issue by Cherkah** [Nyre221/dolphin-quick-view#25] opened 2024-04-15 16:12 UTC
whatever the shortcut assigned to the qview or not, the plugin create crashes with dolphin.

> (you can activate the shortcut as you want)

In Dolphin,the "Space" shortcut is assigned by default to the folder/file selection function.
since installing qview, the "Space" shortcut is confused with that of the plugin.

i do not have any logs to provide to you.

**Comment by Nyre221** [comment] 2024-04-15 18:51
> whatever the shortcut assigned to the qview or not, the plugin create crashes with dolphin.

QuickView alone cannot crash dolphin as it is a totally separate application that uses dbus to interact with dolphin.

>since installing qview, the "Space" shortcut is confused with that of the plugin.

It can't be from the moment of installation because Quickview doesn't autoconfigure any activation shortcuts.

>In Dolphin,the "Space" shortcut is assigned by default to the folder/file selection function.

Press `CTRL+ALT+,` and remove the folder selection shortcut.

The reason for the crash seems to be,  from the tests I did, due to some bug in dolphin. It's not a matter of conflicts between global and non-global shortcuts, but it seems to just be dolphin crashing when the file and folder selection shortcut (Space) is invoked and no file is selected.

I suggest you report this bug to the Dolphin developers.
You can disable the shortcut from the configuration menu in dolphin( `CTRL+ALT+,` ).

```
KCrash: Application 'dolphin' crashing... crashRecursionCounter = 2
KCrash: Application Name = dolphin path = /usr/bin pid = 23591
KCrash: Arguments: /usr/bin/dolphin 
```
edit:
@Cherkah 
Just to be sure I'll try installing Kde Neon on a virtual machine and see what the problem is.
Could you tell me what version of dolphin are you using (dolphin --version)?
I think the problem is on dolphin 24.02.2

**Comment by Nyre221** [comment] 2024-04-15 20:24
@Cherkah 
> Just to be sure I'll try installing Kde Neon on a virtual machine and see what the problem is.
> Could you tell me what version of dolphin are you using (dolphin --version)?
> I think the problem is on dolphin 24.02.2

I downloaded and updated (without installing) Kde neon unstable edition and the problem only appears in version 24.04.02 of Dolphin (not on 24.04.01), could you confirm which version of dolphin you are using?

For now you can simply remove the selection mode shortcut in dolphin(press `CTRL+ALT+,` in dolphin) to avoid it crashing.

Have a nice day.

**Comment by Nyre221** [comment] 2024-04-15 20:30
@Cherkah 
Someone has already reported it: https://bugs.kde.org/show_bug.cgi?id=485599

**Comment by Cherkah** [comment] 2024-04-15 20:32
> The reason for the crash seems to be, from the tests I did, due to some bug in dolphin.

you'r probably right. 

> I suggest you report this bug to the Dolphin developers. 

i already did it. in case you want to contribute the link is (there)[https://bugs.kde.org/show_bug.cgi?id=485599]

> dolphin --version

24.02.2
extra system info: Operating System: EndeavourOS 
KDE Plasma Version: 6.0.3
KDE Frameworks Version: 6.1.0
Qt Version: 6.7.0

> For now you can simply remove the selection mode shortcut in dolphin(press CTRL+ALT+, in dolphin) to avoid it crashing.

I will

**Comment by Nyre221** [comment] 2024-04-16 14:16
> i already did it. in case you want to contribute the link is (there)[https://bugs.kde.org/show_bug.cgi?id=485599]

Reported

I am closing this report as it is not a problem related to QuickView.

**Closed as completed by Nyre221** 2024-04-16 14:16 UTC

**Comment by Cherkah** [comment] 2024-04-16 14:20
thanks
