### ISSUE TITLE
A small error in Manjaro's requirements

### ISSUE THREAD

**Issue by Terkyz** [Nyre221/dolphin-quick-view#2] opened 2023-09-11 00:02 UTC
I use Garuda but I think it is the same, the qpageview package does not exist and is called python-qpageview.

**Comment by shawnk-23** [comment] 2023-09-11 01:20
> I use Garuda but I think it is the same, the qpageview package does not exist and is called python-qpageview.

Hey Terkyz, I'm on Garuda too. Did you manage to install it successfully? if so how did you go about it? Im getting 'no module named 'qpageview' error when I run ./quick_view.pyz anyfile.txt as a test. I would appreciate it very much if either Nyre221 or Terkyz can help me installing this. Thank you in advance.

**Comment by RedBearAK** [comment] 2023-09-11 01:22
Looks like my issue (#3) may be a duplicate of this, but I included a lot of the terminal output I saw while trying to fix it. Not sure how to fix it yet.

**Comment by shawnk-23** [comment] 2023-09-11 01:24
> Looks like my issue (#3) may be a duplicate of this, but I included a lot of the terminal output I saw while trying to fix it. Not sure how to fix it yet.

LOL. it looks like we replied each other at the same time. I just confirmed this error on your earlier comment.

**Comment by Terkyz** [comment] 2023-09-11 01:33
Honestly I had no problem installing it correctly apart from the fact that the dependency has another name, the only thing I did was to run the commands from README-REQUIREMENTS.txt but when Pacman told me that qpageview did not exist I looked for it in Octopi and installed it from there, then I ran the other commands and now everything works, at least from the context menu.

And @shawnk-23 I think your problem is related to you trying to run quick-view from the quick_view.pyz file and not from dolphin_quick_view_view_shortcut.sh, just did the test with an image and if I try to open quick-view with the quick_view.pyz file instead of dolphin_quick_view_shortcut.sh it throws several errors in the terminal. 

Now that I remember, I also installed antiword from Octopi when the other packages installed fine except qpageview.

**Comment by shawnk-23** [comment] 2023-09-11 01:44
Good to know htat I'm not the only one. I hope this will be fixed soon. I've been waiting for a project like this to come back since klook stopped working. I'm really excited.

> Honestly I had no problem installing it correctly apart from the fact that the dependency has another name, the only thing I did was to run the commands from README-REQUIREMENTS.txt but when Pacman told me that qpageview did not exist I looked for it in Octopi and installed it from there, then I ran the other commands and now everything works, at least from the context menu.
> 
> And @shawnk-23 I think your problem is related to you trying to run quick-view from the quick_view.pyz file and not from dolphin_quick_view_view_shortcut.sh, just did the test with an image and if I try to open quick-view with the quick_view.pyz file instead of dolphin_quick_view_view_shortcut.sh it throws several errors in the terminal.

I tried to open quick-view with dolphin_quick_view_shortcut.sh initially but no luck. I figured i should try quick_view.pyz to troubleshoot it after looking at the code. Not sure if it was due to the same issue then... I had to install python-qpageview bc there was no qpageview like you mentioned but mine's not working.

**Comment by RedBearAK** [comment] 2023-09-11 01:48
Got past it on Fedora 38 by installing: 

```sh
sudo dnf install python3-qpageview
```

**Comment by shawnk-23** [comment] 2023-09-11 01:48
> Good to know htat I'm not the only one. I hope this will be fixed soon. I've been waiting for a project like this to come back since klook stopped working. I'm really excited.
> 
> > Honestly I had no problem installing it correctly apart from the fact that the dependency has another name, the only thing I did was to run the commands from README-REQUIREMENTS.txt but when Pacman told me that qpageview did not exist I looked for it in Octopi and installed it from there, then I ran the other commands and now everything works, at least from the context menu.
> > And @shawnk-23 I think your problem is related to you trying to run quick-view from the quick_view.pyz file and not from dolphin_quick_view_view_shortcut.sh, just did the test with an image and if I try to open quick-view with the quick_view.pyz file instead of dolphin_quick_view_view_shortcut.sh it throws several errors in the terminal.
> 
> I tried to open quick-view with dolphin_quick_view_shortcut.sh initially but no luck. I figured i should try quick_view.pyz to troubleshoot it after looking at the code. Not sure if it was due to the same issue then... I had to install python-qpageview bc there was no qpageview like you mentioned but mine's not working.

when I tried ./dolphin_quick_view_shortcut.sh /home/usr/Downloads/sample.pdf, nothing happens. no error/no quick view window pops up

**Comment by RedBearAK** [comment] 2023-09-11 01:51
@shawnk-23 

Try to follow the systemd journal when you open the Dolphin window and try to Quick View a file from the context menu in Dolphin. 

```sh
journalctl -b -f -n100
```

**Comment by shawnk-23** [comment] 2023-09-11 01:57
> 

I get pretty much the same error that you're getting when I try quick view from context menu in dolphin:

File "/home/shawn/.config/quick_view/quick_view.pyz/__main__.py", line 1, in <module>
File "/home/shawn/.config/quick_view/quick_view.pyz/quick_view.py", line 8, in <module>
File "/home/shawn/.config/quick_view/quick_view.pyz/Page_viewer.py", line 1, in <module>
ModuleNotFoundError: No module named 'qpageview'

**Comment by shawnk-23** [comment] 2023-09-11 02:00
> I get pretty much the same error that you're getting when I try quick view from context menu in dolphin:
> 
> File "/home/shawn/.config/quick_view/quick_view.pyz/**main**.py", line 1, in File "/home/shawn/.config/quick_view/quick_view.pyz/quick_view.py", line 8, in File "/home/shawn/.config/quick_view/quick_view.pyz/Page_viewer.py", line 1, in ModuleNotFoundError: No module named 'qpageview'



> @shawnk-23
> 
> Try to follow the systemd journal when you open the Dolphin window and try to Quick View a file from the context menu in Dolphin.
> 
> ```shell
> journalctl -b -f -n100
> ```

@shawnk-23

Try to follow the systemd journal when you open the Dolphin window and try to Quick View a file from the context menu in Dolphin.

```shell
journalctl -b -f -n100
```


> @shawnk-23
> 
> Try to follow the systemd journal when you open the Dolphin window and try to Quick View a file from the context menu in Dolphin.
> 
> ```shell
> journalctl -b -f -n100
> ```

I get pretty much the same error that you're getting when I try quick view from context menu in dolphin:

File "/home/shawn/.config/quick_view/quick_view.pyz/main.py", line 1, in
File "/home/shawn/.config/quick_view/quick_view.pyz/quick_view.py", line 8, in
File "/home/shawn/.config/quick_view/quick_view.pyz/Page_viewer.py", line 1, in
ModuleNotFoundError: No module named 'qpageview'

**Comment by RedBearAK** [comment] 2023-09-11 02:08
It's odd that didn't go away for you after installing `python-qpageview`. It did for me with the `python3-qpageview` package.

**Comment by shawnk-23** [comment] 2023-09-11 02:13
> It's odd that didn't go away for you after installing `python-qpageview`. It did for me with the `python3-qpageview` package.

did you have to start all installation processes over again when you install python-qpageview? the thing is I install python-qpageview correctly from the beginning. the only error I got was with python-pyexcel-xlsx.

**Comment by RedBearAK** [comment] 2023-09-11 02:19
@shawnk-23 

> did you have to start all installation processes over again when you install python-qpageview? the thing is I install python-qpageview correctly from the beginning. the only error I got was with python-pyexcel-xlsx.

Not sure how to fix your issue on an Arch-based distro. On Fedora some of those packages were installed with `pip`, not the native package manager (DNF). But the one that fixed my issue was installed with DNF, after failing when I tried to install the module with `pip`. 

```
fedora 38
sudo dnf install python3-qt5 python3-pip antiword python3-poppler-qt5 python3-qpageview gstreamer1-plugin-libav gstreamer1-plugin-openh264
pip install pyexcel pyexcel-xls pyexcel-xlsx
pip install textract


manjaro:
sudo pacman -S python-pyqt5 python-poppler-qt5 python-pip python-qpageview antiword
yay -S python-pyexcel python-pyexcel-xls python-pyexcel-xlsx
pip install textract --break-system-packages
```

**Comment by shawnk-23** [comment] 2023-09-11 02:20
> Honestly I had no problem installing it correctly apart from the fact that the dependency has another name, the only thing I did was to run the commands from README-REQUIREMENTS.txt but when Pacman told me that qpageview did not exist I looked for it in Octopi and installed it from there, then I ran the other commands and now everything works, at least from the context menu.
> 
> And @shawnk-23 I think your problem is related to you trying to run quick-view from the quick_view.pyz file and not from dolphin_quick_view_view_shortcut.sh, just did the test with an image and if I try to open quick-view with the quick_view.pyz file instead of dolphin_quick_view_shortcut.sh it throws several errors in the terminal.
> 
> Now that I remember, I also installed antiword from Octopi when the other packages installed fine except qpageview.

Did you have issue installing python-pyexcel-xlsx from your garuda by any chance? I'm getting following eerror: 

:: Proceed with install? [Y/n] y
:: (1/1) Parsing SRCINFO: python-pyexcel-xlsx
resolving dependencies...
looking for conflicting packages...

Packages (2) python-et-xmlfile-1.1-4  python-openpyxl-3.1.2-2

Total Download Size:   0.46 MiB
Total Installed Size:  3.16 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 python-openpyxl-3.1.2-2-any.pkg.tar.zst failed to download
error: failed retrieving file 'python-openpyxl-3.1.2-2-any.pkg.tar.zst' from mirror.csclub.uwaterloo.ca : The requested URL returned error: 404
error: failed retrieving file 'python-openpyxl-3.1.2-2-any.pkg.tar.zst' from archlinux.uk.mirror.allworldit.com : The requested URL returned error: 404
error: failed retrieving file 'python-openpyxl-3.1.2-2-any.pkg.tar.zst' from asia.mirror.pkgbuild.com : The requested URL returned error: 404
error: failed retrieving file 'python-openpyxl-3.1.2-2-any.pkg.tar.zst' from mirror.theo546.fr : The requested URL returned error: 404
error: failed retrieving file 'python-openpyxl-3.1.2-2-any.pkg.tar.zst' from mirror.chaoticum.net : Could not resolve host: mirror.chaoticum.net
warning: too many errors from mirror.chaoticum.net, skipping for the remainder of this transaction
warning: failed to retrieve some files
error: failed to commit transaction (invalid url for server)
Errors occurred, no packages were upgraded.
 -> error installing repo packages

**Comment by shawnk-23** [comment] 2023-09-11 02:22
> @shawnk-23
> 
> > did you have to start all installation processes over again when you install python-qpageview? the thing is I install python-qpageview correctly from the beginning. the only error I got was with python-pyexcel-xlsx.
> 
> Not sure how to fix your issue on an Arch-based distro. On Fedora some of those packages were installed with `pip`, not the native package manager (DNF). But the one that fixed my issue was installed with DNF, after failing when I tried to install the module with `pip`.
> 
> ```
> fedora 38
> sudo dnf install python3-qt5 python3-pip antiword python3-poppler-qt5 python3-qpageview gstreamer1-plugin-libav gstreamer1-plugin-openh264
> pip install pyexcel pyexcel-xls pyexcel-xlsx
> pip install textract
> 
> 
> manjaro:
> sudo pacman -S python-pyqt5 python-poppler-qt5 python-pip python-qpageview antiword
> yay -S python-pyexcel python-pyexcel-xls python-pyexcel-xlsx
> pip install textract --break-system-packages
> ```

hmm... frustrated.  i was so excited to try this. :(

**Comment by RedBearAK** [comment] 2023-09-11 02:23
@Terkyz 

Even after a web search I still have no idea what "Octopi" refers to. The main thing that comes up is a distro for Raspberry Pi for using OctoPrint to control 3D printers. 

I solved my problem on Fedora, but some context would probably be helpful for others reading this.

**Comment by Nyre221** [comment] 2023-09-11 02:39
@shawnk-23 
> mm... frustrated. i was so excited to try this. :(

you can force the installation using pip: 
"pip install qpageview" or "pip install qpageview --break-system-packages"

"pip install pyexcel pyexcel-xls pyexcel-xlsx" or "pip install pyexcel pyexcel-xls pyexcel-xlsx --break-system-packages"


Tomorrow I'll help you more, I don't have time now.

**Comment by shawnk-23** [comment] 2023-09-11 05:51
> @shawnk-23
> 
> > mm... frustrated. i was so excited to try this. :(
> 
> you can force the installation using pip: "pip install qpageview" or "pip install qpageview --break-system-packages"
> 
> "pip install pyexcel pyexcel-xls pyexcel-xlsx" or "pip install pyexcel pyexcel-xls pyexcel-xlsx --break-system-packages"
> 
> Tomorrow I'll help you more, I don't have time now.

I finally got this working by reinstalling all the required packages. However, I still don't see pdf and mp4. I did install  python3-qpageview and python3-poppler-qt5. in my package manager, it doesn't exactly call it python3-qpageview. it's just python-qpageview without 3 and poppler-qt5 rather than python3-poppler-qt5. As for mp4, which gstreamer library is needed? I think I have all necessary gstreamer libraries installed.

**Comment by Nyre221** [comment] 2023-09-11 13:57
@shawnk-23 
you need "python-poppler-qt5" and not "poppler-qt5" to see the pdfs

python3-poppler-qt5 is for fedora

> which gstreamer library is needed? I think I have all necessary gstreamer libraries installed.

In my clean install of manjaro the necessary gstreamer libraries were already installed.
Try: "~/.config/quick_view/quick_view.pyz /path/to/video.mp4" and see if it gives you errors

Those normally needed are gstreamer1-plugin-libav  and gstreamer1-plugin-openh264 (openh264 is only needed on Fedora. ) 

On manjaro the command should be this: sudo pamac install gst-libav

Tell me if the command is the right one and if it lets you open mp4 files.

**Comment by Nyre221** [comment] 2023-09-12 11:47
I'm closing this report: the original problem was caused by incorrectly writing the required dependencies.

@shawnk-23 

If you need, feel free to open another report dedicated to your problem.

**Closed as completed by Nyre221** 2023-09-12 11:47 UTC
